services:
  - type: web
    name: corecommerce-api
    runtime: python
    branch: main
    plan: free
    autoDeploy: true
    healthCheckPath: /admin/login/

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input

    startCommand: |
      python manage.py migrate && gunicorn core_comerce.wsgi:application

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-core-comerce
          property: connectionString
          
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"
